input_data:
  daily_climate_data_2023:  '../data/raw/daily_climate_2023.csv'
  daily_climate_data_2024:  '../data/raw/daily_climate_2024.csv'
  sales_data_2023: '../data/raw/veronicas_sales_2023.csv'
  sales_data_2024: '../data/raw/veronicas_sales_2024.csv'

output_data:
  merged_climate_data:  '../data/clean/merged_climate.csv'
  merged_sales_data: '../data/clean/merged_sales.csv'
  cleaned_merged_climate_sales: '../data/clean/veronicas_cleaned_df.csv'